### PR TITLE
Revert changes not compatible with Scala 2.10

### LINKED ISSUE #64: test runner does not compile in 2.10.4
/home/ubuntu/mesos-spark-integration-tests/test-runner/src/main/scala/com/typesafe/spark/test/mesos/framework/runners/Utils.scala:98: value lineStream is not a member of scala.sys.process.ProcessBuilder

we need to fix this in general in order to test spark with 2.10.x versions.

### PR DESCRIPTION
**Pull request by skyluc**
Fixes #64

### CODE REVIEW

**Comment by dragos** [comment]
LGTM
